---
title: "Spatio-Temporal Bayesian Modeling for Mobile Edge Computing"
author: "Laha Ale"
date: "April 27, 2019"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = F,message = F)
```



## Data cleaned but still have spatial outlier

```{r data,cho = TRUE}
library(dplyr)
library(lubridate)


data <- read.csv("data/clean.csv")

# format time
data <- data %>% mutate(start_time = ymd_hms(start_time)) %>%
    mutate(end_time = ymd_hms(end_time))

# compute connected time
data["con_time"] <- as.numeric(difftime(ymd_hms(data$end_time),
                                        ymd_hms(data$start_time),units = "secs"))
head(data)
```

## Data Exploratory

```{r 3dplot}
library(plotly)
sum_time <- data %>% group_by(long,lat) %>% summarise(sum_time = sum(con_time))
p <- plot_ly(sum_time, x =~long, y = ~lat, z = ~sum_time,type = "scatter3d")
p

```

## Data Dxploratory

```{r 3dmesh}
p <- plot_ly(sum_time, x =~long, y = ~lat, z = ~sum_time, type = 'mesh3d')
p

```


## Data Dxploratory

```{r 3map1}
Sys.setenv('MAPBOX_TOKEN' = 'pk.eyJ1IjoiYWluaWxhaGEiLCJhIjoiY2p1enYzbm9hMWNzMTQzbXcyNWt0M3VwNyJ9._PwdGJ4wfOnzfZ9Ux9Oxvw')

p <- plot_mapbox(data, x = ~long, y = ~lat) %>%
  add_paths(size = I(2)) %>%
  add_segments(x = -100, xend = -50, y = 50, 75)

p

```


## Data Dxploratory

```{r 3map2}
#Run R commands
p <- data %>%
  plot_mapbox(lat = ~lat, lon = ~long,
              split = ~class, size=2,
              mode = 'scattermapbox', hoverinfo='user_id') %>%
  layout(title = 'Shanghai Network (by Laha Ale)',
         font = list(color='white'),
         plot_bgcolor = '#191A1A', paper_bgcolor = '#191A1A',
         mapbox = list(style = 'dark'),
         legend = list(orientation = 'h',
                       font = list(size = 8)),
         margin = list(l = 25, r = 25,
                       b = 25, t = 25,
                       pad = 2))
p

```




## Remove spatial outerlier

```{r 3map_outer}
library(rgdal)     # R wrapper around GDAL/OGR
library(ggplot2)   # for general plotting
library(ggmap)    # for fortifying shapefiles
library(sf)

shapefile <- st_read("./data/shp/shang_dis_merged.shp")
name_shape <- shapefile[,'Name']
plot_ly(name_shape,color = ~Name )
name_shape

ptx <- sum_time[,1:2]
crdref <- CRS('+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0')
ptx <- SpatialPoints(ptx, proj4string=crdref)

ptsdf <- SpatialPointsDataFrame(ptx, data=data.frame(sum_time$sum_time))
ptsdf
library(raster)
plot(name_shape$geometry,border="blue", col="gray")
points(ptsdf,pch=20, cex=1, col="red")

```


## Clean data map
```{r Clean_map}
p <- data %>%
  plot_mapbox(lat = ~lat, lon = ~long,
              split = ~class, size=2,
              mode = 'scattermapbox', hoverinfo='user_id') %>%
  layout(title = 'Shanghai Network (by Laha Ale)',
         font = list(color='white'),
         plot_bgcolor = '#191A1A', paper_bgcolor = '#191A1A',
         mapbox = list(style = 'dark'),
         legend = list(orientation = 'h',
                       font = list(size = 8)),
         margin = list(l = 25, r = 25,
                       b = 25, t = 25,
                       pad = 2))
p

```

## add round started time to minutes

```{r Clean_map}
p <- data %>%
data <- data %>% mutate(rnd_strat = minute(round_date(start_time, "minute"))) %>%
      mutate(rnd_end = minute(round_date(end_time, "minute")))

sum_time <- data %>% group_by(long,lat,rnd_strat) %>% summarise(sum_time = sum(con_time))




p <- plot_ly(sum_time, x =~long,
             y = ~lat, z = ~sum_time,
             color = ~rnd_strat,
             colors = c('#CCFF00', '#0000CC'),type = "scatter3d")
p


```






## Geospatial Visulization

```{r Geostat_viso}
library(MBA)
library(fields)

coords <- as.matrix(data[,c("long","lat")])
x.res <- 200; y.res <- 200
surf <- mba.surf(cbind(coords,
                       data$con_time),
                 no.X=x.res, no.Y=y.res, h=5,
                 m=2, extend=FALSE)$xyz.est
image.plot(surf, xaxs = "r",
           yaxs = "r", xlab="long",
           ylab="lat",
           main="Connection Time" )
points(coords)
contour(surf,add = T)





library(rgl)
library(RColorBrewer)
col.br <- colorRampPalette(c("blue", "cyan", "yellow", "red"))
col <- rbind(0, cbind(matrix(drape.color(surf[[3]],
                                         col = col.br(25)), x.res - 1, y.res-1), 0))
surface3d(surf[[1]], surf[[2]], surf[[3]], col = abs(col))
axes3d()
title3d(main = "strata", xlab = "long", ylab = "lat", zlab = "conn_time")
drape.plot(surf[[1]], surf[[2]], surf[[3]],
           col = col.br(150), theta = 225, phi = 20,
           border = FALSE, add.legend = FALSE,
           xlab = "long", ylab = "lat", zlab = "conn_time")
image.plot(zlim = range(surf[[3]], na.rm = TRUE),
           legend.only = TRUE, horizontal = FALSE)

```

### Virogram
### Kringing
### Bayesian
### Spatio-time Baysian





